name: github-actions
on:
  push:
    branches:
    # Limit to the `master` branch
    - master
  schedule:
    # Run every 5 minutes
    - cron:  '*/5 * * * *'
jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the workflow
      run: |
        set -e
        set -x
        npm install
        node .
        authorization="Authorization: token ${{secrets.API_TOKEN}}"
        description=$(cat countdown.now)
        curl -H "$authorization" -X PATCH https://api.github.com/repos/tomashubelbauer/ocr -d '{"description":"'"$description"'"}'
    # Note that the artifacts can't be downloaded raw, they'll always be zipped
    # https://github.com/actions/upload-artifact#zipped-artifact-downloads
    - uses: actions/upload-artifact@v2
      with:
        name: drop
        path: |
          live_user_ludwig-1920x1080.jpg
          extract.png
          countdown.now
