name: main
on:
  push:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the source code
      uses: actions/checkout@v3
    - name: Run the workflow
      run: |
        set -e
        set -x
        npm install
        node .
        authorization="Authorization: token ${{secrets.API_TOKEN}}"
        description=$(cat countdown.now)
        curl -H "$authorization" -X PATCH ${{github.api_url}}/repos/${{github.repository}} -d '{"description":"'"$description"'"}'
    # Note that the artifacts can't be downloaded raw, they'll always be zipped
    # https://github.com/actions/upload-artifact#zipped-artifact-downloads
    - uses: actions/upload-artifact@v2
      with:
        name: drop
        path: |
          live_user_ludwig-1920x1080.jpg
          extract.png
          countdown.now
